# -------------------------------------------------- #
# Outline of the configuration file ---------------- #
# 1. Default settings ------------------------------ #
# 2. Fundamental settings of hydra ----------------- #
# 3. Experiment Settings --------------------------- #
# 4. Network Settings ------------------------------ #
# -------------------------------------------------- #
