# -------------------------------------------------- #
# Outline of the configuration file ---------------- #
# 1. Default settings ------------------------------ #
# 2. Fundamental settings of hydra ----------------- #
# 3. Experiment Settings --------------------------- #
# 4. Network Settings ------------------------------ #
# -------------------------------------------------- #


# -------------------------------------------------- #
# Default settings --------------------------------- #
# -------------------------------------------------- #
defaults:
  - _self_
  - custom_configs: empty


# -------------------------------------------------- #
# Fundamental settings of hydra -------------------- #
# -------------------------------------------------- #
hydra:
  run:
    dir: ${exp_setting.exp_dir}  # define the path to the experiment directory
  job_logging:
    handlers:
      file:
        filename: ${hydra:runtime.output_dir}/${hydra:job.name}.log  # define the path to the log file


# -------------------------------------------------- #
# Experiment Settings ------------------------------ #
# -------------------------------------------------- #
exp_setting:
  filename: "sample.mp3"
  exp_dir: "output_results/${exp_setting.filename}"
  log_file: ${hydra:runtime.output_dir}/${hydra:job.name}.log

